/*Generated by xorm v0.7.0.0504 2018-11-08 23:44:32, from mysql to MYSQL*/

CREATE TABLE IF NOT EXISTS `star_info` (`id` INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '主键ID', `name_zh` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '中文名', `name_en` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '英文名', `avatar` VARCHAR(255) DEFAULT '' NOT NULL COMMENT '头像', `birthday` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '出生日期', `height` INT(10) DEFAULT 0 NOT NULL COMMENT '身高，单位cm', `weight` INT(10) DEFAULT 0 NOT NULL COMMENT '体重，单位kg', `club` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '俱乐部', `jersy` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '球衣号码以及主打位置', `country` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '国籍', `birthaddress` VARCHAR(255) DEFAULT '' NOT NULL COMMENT '出生地', `feature` VARCHAR(255) DEFAULT '' NOT NULL COMMENT '个人特点', `moreinfo` TEXT NULL COMMENT '更多介绍', `sys_status` TINYINT(4) DEFAULT 0 NOT NULL COMMENT '状态，默认值 0 正常，1 删除', `sys_created` INT(10) DEFAULT 0 NOT NULL COMMENT '创建时间', `sys_updated` INT(10) DEFAULT 0 NOT NULL COMMENT '最后修改时间') ENGINE=InnoDB DEFAULT CHARSET utf8;
INSERT INTO `star_info` (`id`, `name_zh`, `name_en`, `avatar`, `birthday`, `height`, `weight`, `club`, `jersy`, `country`, `birthaddress`, `feature`, `moreinfo`, `sys_status`, `sys_created`, `sys_updated`) VALUES (1, 'C罗', 'Cristiano Ronaldo', 'http://www.sinaimg.cn/lf/sports/wc_2018/player/14937.jpg', '1985-02-05', 187, 83, '皇家马德里', '前锋7号', '葡萄牙', '', '', '', 0, 0, 1529144171);
INSERT INTO `star_info` (`id`, `name_zh`, `name_en`, `avatar`, `birthday`, `height`, `weight`, `club`, `jersy`, `country`, `birthaddress`, `feature`, `moreinfo`, `sys_status`, `sys_created`, `sys_updated`) VALUES (2, '梅西', 'Lionel Messi', 'http://www.sinaimg.cn/lf/sports/wc_2018/player/19054.jpg', '1987-06-24', 170, 72, '巴塞罗那', '前锋10号', '阿根廷', '阿根廷圣菲省罗萨里奥', '', '绰号“新马拉多纳”', 0, 0, 1529135214);
INSERT INTO `star_info` (`id`, `name_zh`, `name_en`, `avatar`, `birthday`, `height`, `weight`, `club`, `jersy`, `country`, `birthaddress`, `feature`, `moreinfo`, `sys_status`, `sys_created`, `sys_updated`) VALUES (3, '穆勒', 'Thomas Müller', 'http://www.sinaimg.cn/lf/sports/wc_2018/player/55634.jpg', '1989-09-13', 186, 75, '拜仁慕尼黑', '前锋13号', '德国', '未知', '未知', '', 0, 0, 1529149343);

CREATE TABLE IF NOT EXISTS `user_info` (`id` INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR(255) NULL, `sys_created` INT(11) NULL, `sys_updated` INT(11) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8;
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (1, 'name', 0, 1541691330);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (2, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (3, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (4, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (5, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (6, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (7, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (8, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (9, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (10, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (11, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (12, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (13, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (14, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (15, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (16, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (17, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (18, '梅西', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (19, 'name', 0, 0);
INSERT INTO `user_info` (`id`, `name`, `sys_created`, `sys_updated`) VALUES (20, '梅西', 0, 0);
